<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Spatie\Permission\Models\Role as ModelsRole;
use Illuminate\Database\Eloquent\Builder;
class Role extends ModelsRole
{
    use HasFactory;
//    public static function getEloquentQuery(): Builder
//    {
//        return parent::getEloquentQuery()
//            ->where('name','!=', 'Super Admin'); // TODO: Change the autogenerated stub
//    }
}
